version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGODB_URL: "mongodb://db:27017/mydb"
  db:
    image: mongo:latest
    arch: amd64
    ports:
      - "27017:27017"
