version: '3.10'
services:
  api:
    build:
      context: /api/.
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - network
    platform: linux/arm64/v8
  db:
    image: mongo
    ports:
      - 27019:27017
    networks:
      - network
    platform: linux/amd64

networks:
  network: