version: '3.0'
services:
  db:
    container_name: db
    image: mongo:${MONGO_VERSION}
    ports:
    - "${MONGO_PORT}:27017"
    volumes:
    - mongo-data:/data/db
    networks:
    - net_A
  server:
    container_name: server
    image: 26karol26/zadanie2:v4
    build: .
    depends_on:
      - db
    ports:
    - "3003:3000"
    networks:
    - net_A

networks:
    net_A:
        external: false
        name: net_A

volumes:
  mongo-data: